[package]
name = "carla_autoware_zenoh_bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh = "0.6.0-beta.1"
carla = "0.5.0"
serde = "1.0.147"
serde_derive = "1.0.147"
cdr = "0.2.4"
atomic_float = "0.1.0"
