[package]
name = "zenoh_carla_bridge"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh = "0.7.0-rc"
carla = "0.6.0"
serde = "1.0.152"
serde_derive = "1.0.152"
cdr = "0.2.4"
atomic_float = "0.1.0"
clap = { version = "4.0.32", features = ["derive"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
carla-ackermann = "0.1.0"
r2r = "0.6.4"
anyhow = { version = "1.0.68", features = ["backtrace"] }
thiserror = "1.0.38"
arc-swap = "1.6.0"
nalgebra = "0.31.4"
ndarray = "0.15.6"
